[project]
name = "pivert-server"
version = "0.0.1-beta"
dependencies = [
    "bcrypt>=4.3.0",
    "cryptography>=45.0.7",
    "fastapi[standard]>=0.116.1",
    "numpy>=2.3.3",
    "pyjwt>=2.10.1",
    "tinydb>=4.8.2",
]

